### ISSUE TITLE
File linking broken

### ISSUE THREAD

**Issue by alexjshepler** [ChandlerVer5/epub2MD#4]
This is the only epub to markdown converter that I found that actually works, even pandoc didn't work for my text book, but the links don't link. They have some weird htmx link

Result:
```
[Chapter 2](fileP7000497027000000000000000000279.xhtml#P7000497027000000000000000000279)
```

Expected:
```
[[Chapter 2 Representing and Manipulating Information |Chapter 2]]
```

**Comment by ChandlerVer5** [comment]
essentially it works by converting html to md files, so the section headings need to rely on the html's A-link headings, but the links should be correct. You could send send me your text book，I will check it.

**Comment by alexjshepler** [comment]
I'm using obsidian for my markdown so the linking between files is done differently (my bad), but yes.

After running `epub2md -m ...` again it outputs a epub file thats larger than the original
<img width="628" alt="image" src="https://github.com/ChandlerVer5/epub2MD/assets/19987488/3f0582db-3c8e-4005-9420-cffc2799eb37">

https://file.io/fyIuStCENNm3
